version: v1.0.14
domain: www.musedam.cc
envs:
- name: DEPLOY_REGION
  value: ""
- name: DATABASE_URI
  value: ""
- name: PAYLOAD_SECRET
  value: ""
- name: REVALIDATION_KEY
  value: ""
- name: SITE_SERVER_URL
  value: ""
- name: NEXT_PRIVATE_DRAFT_SECRET
  value: ""
- name: NEXT_PRIVATE_REVALIDATION_KEY
  value: ""
