export const MUSEDAM_LOGIN_URL = '/auth'
export const BROWSER_EXTENSION_URL =
  'https://chromewebstore.google.com/detail/musedam-collector/acheegccgdmgeibdnjoolajjdnohpanl'
export const BROWSER_EXTENSION_URL_ZH = 'https://tezign.feishu.cn/wiki/wikcnAlxBEhe4KNaEpijwk8lhAh'
export const MUSE_GLOBAL_CHECKOUT_URL = '/settings'
export const MUSE_MAINLAND_CHECKOUT_URL = 'https://app.museai.cc/settings'
export const MUSE_GLOBAL_SERVER_URL = 'https://apigw.musedam.ai'
// export const MUSE_MAINLAND_SERVER_URL = 'https://musedam-service.tezign.com'
export const MUSE_MAINLAND_SERVER_URL = 'https://musedam-service.test.tezign.com'
export const MUSE_GLOBAL_AUTH_URL = 'https://musedam.ai/auth'
// export const MUSE_MAINLAND_AUTH_URL = 'https://musedam.cc/auth'
export const MUSE_MAINLAND_AUTH_URL = 'https://muse-web.test.tezign.com/auth'
export const MUSE_CONTACT_EMAIL = 'contact@musedam.cc'
