apiVersion: apps/v1
kind: Deployment
metadata:
  name: musedam-website
  namespace: musedam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musedam-website
  template:
    metadata:
      labels:
        app: musedam-website
    spec:
      containers:
        - image: musecr.azurecr.cn/muse/musedam-website:{{ .Values.version }}
          imagePullPolicy: Always
          name: musedam-website
          env:
          {{- range .Values.envs }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /zh
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /zh
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      imagePullSecrets:
      - name: registry-azure
---
apiVersion: v1
kind: Service
metadata:
  name: musedam-website-svc
  namespace: musedam
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: musedam-website
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: musedam-website-ingress
  namespace: musedam
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-499"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - secretName: ssl-wildcard-musedam-cc
      hosts:
      - zh.musedam.cc
      - www.musedam.cc
  rules:
    - host: zh.musedam.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musedam-website-svc
                port:
                  number: 3000
    - host: www.musedam.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musedam-website-svc
                port:
                  number: 3000
