apiVersion: v1
kind: Secret
metadata:
  name: ssl-wildcard-musedam-cc
  namespace: musedam
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $.Files.Get "secrets/musedam.cc--wildcard/fullchain.pem" | b64enc }}
  tls.key: |-
    {{ $.Files.Get "secrets/musedam.cc--wildcard/privkey.pem" | b64enc }}
