name: Docker Build and Push

on:
  push:
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: musecr.azurecr.cn
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for Next.js app
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            musecr.azurecr.cn/muse/musedam-website:${{ env.VERSION }}
            musecr.azurecr.cn/muse/musedam-website:latest

      - name: Build and push Docker image for Jobs
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.job
          push: true
          tags: |
            musecr.azurecr.cn/muse/musedam-website:${{ env.VERSION }}-job
            musecr.azurecr.cn/muse/musedam-website:latest-job

      - name: Setup Kubernetes Config And Update Deployment
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_MUSE_CLUSTER }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config use-context muse-aws-cn-prod
          kubectl set image deployment/musedam-website musedam-website=musecr.azurecr.cn/muse/musedam-website:${{ env.VERSION }} --namespace musedam
          kubectl config use-context muse-aws-us-prod
          kubectl set image deployment/musedam-website musedam-website=musecr.azurecr.cn/muse/musedam-website:${{ env.VERSION }} --namespace musedam
